server:
  port: 8092

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/bootcamp_db?serverTimezone=UTC
    username: root
    password: 123456

  sql:
    init:
      mode: always

services:
  capacity:
    base-url: http://localhost:8091/api/v1
  person:
    base-url: http://localhost:8093/api/v1
  report:
    base-url: http://localhost:8094/api/v1